version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    # platform: linux/amd64
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - db-store:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.

volumes:
  db-store: